version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: mongo-server
    ports:
      - 27017:27017

  mongo-seed:
    container_name: mongo-seed
    build: ./db-seed-automation
    links:
      - mongo
    depends_on:
      - mongo

  redis-server:
    container_name: redis-server
    image: 'redis'
    restart: always

  admin-panel:
    container_name: FE_hr_chatbot_admin_panel
    build: ../AdminPanel
    restart: always
    links:
      - mongo
      - redis-server
      - node-app
    depends_on:
      - mongo
      - node-app
      - redis-server
    ports:
          - "3000:80"

  node-app:
    build: .
    container_name: node-server
    restart: always
    ports: 
      - "7000:7000"
    links:
      - mongo
      - redis-server
    depends_on:
      - mongo-seed
      - mongo
      - redis-server
  